// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxB52PrFzKXE0HG8aKHOWs11ZQc3hIh9o',
    appId: '1:886597541521:web:7f107e3dacd930c5e36930',
    messagingSenderId: '886597541521',
    projectId: 'fir-5b4ea',
    authDomain: 'fir-5b4ea.firebaseapp.com',
    storageBucket: 'fir-5b4ea.appspot.com',
    measurementId: 'G-JLFPDBJ38Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlEn_-c7_vkWLPYspYqGkZacureznYUio',
    appId: '1:886597541521:android:0480b68aea7e2a41e36930',
    messagingSenderId: '886597541521',
    projectId: 'fir-5b4ea',
    storageBucket: 'fir-5b4ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeXig6h8wMhRkMWOVmxJoY94QV74y8CfE',
    appId: '1:886597541521:ios:4563246a25dbb476e36930',
    messagingSenderId: '886597541521',
    projectId: 'fir-5b4ea',
    storageBucket: 'fir-5b4ea.appspot.com',
    iosBundleId: 'com.example.firebasee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeXig6h8wMhRkMWOVmxJoY94QV74y8CfE',
    appId: '1:886597541521:ios:a5a5b7e76674ac70e36930',
    messagingSenderId: '886597541521',
    projectId: 'fir-5b4ea',
    storageBucket: 'fir-5b4ea.appspot.com',
    iosBundleId: 'com.example.firebasee.RunnerTests',
  );
}
