// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbwXqCuMbGZn8WZI1FdAeJkSOrb2jBHjI',
    appId: '1:351025293902:web:a4b91d1acdcb1c54f0f11f',
    messagingSenderId: '351025293902',
    projectId: 'coffe-app-ab64c',
    authDomain: 'coffe-app-ab64c.firebaseapp.com',
    storageBucket: 'coffe-app-ab64c.appspot.com',
    measurementId: 'G-8WHGJL5FDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-YfePTUJ88D6ewTpl7Gkv8sDkipHG4c',
    appId: '1:351025293902:android:e2758e31f7b2bd6ff0f11f',
    messagingSenderId: '351025293902',
    projectId: 'coffe-app-ab64c',
    storageBucket: 'coffe-app-ab64c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa-vF5fPcxXn4CWzkm81rCpG-OZGoMkjM',
    appId: '1:351025293902:ios:d15685279c4bed39f0f11f',
    messagingSenderId: '351025293902',
    projectId: 'coffe-app-ab64c',
    storageBucket: 'coffe-app-ab64c.appspot.com',
    iosBundleId: 'com.example.coffeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa-vF5fPcxXn4CWzkm81rCpG-OZGoMkjM',
    appId: '1:351025293902:ios:2254c1b0cac0f829f0f11f',
    messagingSenderId: '351025293902',
    projectId: 'coffe-app-ab64c',
    storageBucket: 'coffe-app-ab64c.appspot.com',
    iosBundleId: 'com.example.coffeApp.RunnerTests',
  );
}
